### ISSUE TITLE
USER STORY: ADD TASK

### ISSUE THREAD

**Issue by brightigiemokha** [brightigiemokha/django_todo#10]
### ADD TASK
***
### USER STORY
As a registered User, **I want to Add Task**, so that its **details would be added to the User profile in database**
***
### ACCEPTANCE CRITERIA
- [x] The user must be logged in as a registered user to access the "Task Todo" feature.
- [x] There should be a clearly visible button for adding a new Task Todo on the website
- [x] The user should be able to enter the following information: Task title (mandatry) and task details..
- [x] There should be a clearly visible button to save new Task Todo on the website
***
### TASKS

- [x] User Authentication: Implement user authentication to ensure that only registered users can access the "Task Todo" feature.
- [x] UI/UX Design: Design and implement a user-friendly interface with a clear button or option for adding a Task Todo.
- [x] Input Form: Create an input form that includes fields for Title, Description.
- [x] Database Integration: Set up the database schema to store book information, including title, author, image URL, short description, and full description
***
