### ISSUE TITLE
USER STORY: VIEW TASK

### ISSUE THREAD

**Issue by brightigiemokha** [brightigiemokha/django_todo#13]
### VIEWING TASK TODO
***
### USER STORY
As a registered User **i want to View task** so as to **view full details** of task
***
### ACCEPTANCE CRITERIA
- [x] The user must be logged in as a registered user to access the Task view feature.
- [x] There should be a visible and accessible button to view Task information.
- [x] When the user clicks the view Task option, they should be directed to a Task view  form.
- [x] The View Task should display the full information of the task todo in complete details (title, descriptions).
***
### TASKS
- [x] User Authentication: Implement user authentication to ensure that only registered users can access the Task view feature.
- [x]  UI Design and Layout: Design and implement the user interface for Viewing Task, including the placement of buttons and forms.
- [x] View Task Form: Create a View Task form that includes fields for title, descriptions. Connect this form to the database to populate with the current Task todo information.
***
