### ISSUE TITLE
USER STORY: ADMIN

### ISSUE THREAD

**Issue by brightigiemokha** [brightigiemokha/django_todo#5]
###ADMIN USER

***
### USER STORY
As Admin User _i want to_ be able to log in to the Admin page of **"Task Todo website"** _so i_ can control the activities on the site
***
### ACCEPTANCE CRITERIA

- [x] There is a Login form accessible from the Admin Page
- [x] The login page form includes fields for username and  password.

***
### TASKS

- [x] Create the django admin form with appropriate fields 
- [x] Create a SuperUser Account

***

**Comment by brightigiemokha** [comment]
admin login page worked
