### ISSUE TITLE
USER STORY: LOGIN

### ISSUE THREAD

**Issue by brightigiemokha** [brightigiemokha/django_todo#7]
### USER LOGIN
***
### USER STORY
As a registered user, **I want to** be able to Loginto my account on the "Task Todo" website, **so that I** can access my account.
***
### ACCEPTANCE CRITERIA

- [x] There is a Login form accessible from the website's homepage.
- [x] The Login form includes fields for username and password .
- [x] The User is redirected to the Profile page unpon successful login
- [x] Users receive an error message if the provided Login details are incorrect.
***
### TASKS

- [x] Create the Login form with appropriate fields and styling.
- [x]  Implement server-side validation and error handling for registration.
- [x] Setup Login Redirect

**Comment by brightigiemokha** [comment]
user login page is perfect, error is shown for wrong login details
