### ISSUE TITLE
USER STORY: ACCOUNT FEATURES

### ISSUE THREAD

**Issue by brightigiemokha** [brightigiemokha/django_todo#8]
### EPIC: FUNCTIONS

***
### USER STORY
As a registered User **i want to** be able to perform task on my account **so i can** control my day to day activities
***
### ACCEPTANCE CRITERIA

- [x] User can add task to their Task todo account easily
- [x] User can Edit Task on their account easily
- [x] User can delete  unwanted task from their account easily
- [x] User can make task as completed on their account easily
***
### TASKS

- [x] Create an Edit Button that take user to the Edit page
- [x] Create a Delete Button that takes unwanted task away
- [x] Create a confirmation notification to confirm if user really want to delete
- [x] Create a Add Button for user to add task to account
***
