### ISSUE TITLE
USER STORY: ADMIN FEATURES

### ISSUE THREAD

**Issue by brightigiemokha** [brightigiemokha/django_todo#9]
### EPIC: ADMIN FEATURES

***
### USER STORY
As an Admin **i want to** be able to control site backend **so as to** control and maintain site and it activities and usage
***
### ACCEPTANCE CRITERIA

- [x] Admin should be able to Delete User who violate site policy
- [x] Admin should be able to Verify User
- [x] Admin should be able to Delete Task
- [x] Admin should be able to Create Group
- [x] Admin should be able to Create User
***
### TASKS
_A single unit of work broken down from the defined user story_
- [x] Set admin to Data base

***

**Comment by brightigiemokha** [comment]
admin can delete user and have been connected to database

**Comment by brightigiemokha** [comment]
Admin can delete user

**Comment by brightigiemokha** [comment]
admin can delete task
